waykey press KEY_LEFTSHIFT
waykey click KEY_H
waykey release KEY_LEFTSHIFT
waykey click KEY_E
waykey click KEY_L
waykey click KEY_L
waykey click KEY_O
waykey click KEY_SPACE
waykey press KEY_LEFTSHIFT
waykey click KEY_W
waykey release KEY_LEFTSHIFT
waykey click KEY_O
waykey click KEY_R
waykey click KEY_L
waykey click KEY_D
waykey press KEY_LEFTSHIFT
waykey click KEY_1
waykey release KEY_LEFTSHIFT
